### ISSUE TITLE
new candles

### ISSUE THREAD

**Issue by davoodinthebox** [diyews/tradingview-angular-example#1]
Hi. Your chart default time interval is 1 minute. after run your project every 3 seconds it generate a new candle so I think it is wrong. isn't? how to correct that issue? I mean in period of 1 minute if there are 10 updates they shoud update the last candle except for creating 10 new candles

**Comment by diyews** [comment]
**Sorry** for replying too late, hope your case had already done.Even then, I am going to tell what I did.

> I mean in period of 1 minute if there are 10 updates they shoud update the last candle except for creating 10 new candles

Of course you are right. First have a look of this [line](https://github.com/diyews/tradingview-angular-example/blob/99a551673460dc80989cd61cf93232da61c13cd4/src/app/providers/mock.service.ts#L16).

>     Object.assign(obj, BTC_PRICE_LIST[this.dataIndex], { time });
In the production, people might not change the data from the server except formatting data. The data's timestamp should be same in the same period(eg: 1 min), then just push the data to the [callback](https://github.com/diyews/tradingview-angular-example/blob/99a551673460dc80989cd61cf93232da61c13cd4/src/app/tv/tv.component.ts#L144), tradingview will update or create a new one depend on the timestamp.
It's to say that this issue won't happen in production, if it does, frontend should check the period and the returned data's timestamp.

In this example I just push new data to the tv every 3 sec ignore the period. So, if you want to update the data in 1 min, just modify the new data's timestamp to current minute in the `MockService`.

**Comment by diyews** [comment]
I had make a commit now the chart behaves what you expect, thank you!
