### ISSUE TITLE
集成问题

### ISSUE THREAD

**Issue by fyzh88** [diyews/tradingview-angular-example#3]
如何把charting_library集成到angular中，中间需要经过什么处理？

**Comment by diyews** [comment]
Tradingview 的库应该有一个 `charting_library/`, 放到 `src/assets/vendors/` 下面就可以了，如果还不行看看是不是 [路径](https://github.com/diyews/tradingview-angular-example/blob/9f618a5b0dbcba3f2cd89ea7726cb60b820d4437/angular.json#L33) 的问题。
或者在 index.html 引入全局js， 创建tv 组件是使用`window.TradingView.widget`， [代码位置](https://github.com/diyews/tradingview-angular-example/blob/9f618a5b0dbcba3f2cd89ea7726cb60b820d4437/src/app/tv/tv.component.ts#L50).
